mkdir -p rawnind_jddc/src/rawnind/libs
mkdir -p rawnind_jddc/src/rawnind/models
mkdir -p rawnind_jddc/src/rawnind/tools
mkdir -p rawnind_jddc/src/rawnind/tests
mkdir -p rawnind_jddc/src/rawnind/config
mkdir -p rawnind_jddc/src/rawnind/paper_scripts
mkdir -p rawnind_jddc/src/rawnind/plot_cfg
mkdir -p rawnind_jddc/src/rawnind/scripts
mkdir -p rawnind_jddc/src/rawnind/onetimescripts
mkdir -p rawnind_jddc/src/common/libs
mkdir -p rawnind_jddc/src/common/tools
mkdir -p rawnind_jddc/src/common/extlibs

cp libs/abstract_trainer.py rawnind_jddc/src/rawnind/libs/
cp ../common/libs/json_saver.py rawnind_jddc/src/common/libs/
cp ../common/libs/pt_helpers.py rawnind_jddc/src/common/libs/
cp ../common/libs/np_imgops.py rawnind_jddc/src/common/libs/
cp ../common/libs/libimganalysis.py rawnind_jddc/src/common/libs/
cp ../common/libs/pt_ops.py rawnind_jddc/src/common/libs/
cp ../common/libs/pt_losses.py rawnind_jddc/src/common/libs/
cp ../common/libs/utilities.py rawnind_jddc/src/common/libs/
cp ../common/libs/locking.py rawnind_jddc/src/common/libs/
cp ../common/tools/save_src.py rawnind_jddc/src/common/tools/
cp libs/rawproc.py rawnind_jddc/src/rawnind/libs/
cp libs/rawds.py rawnind_jddc/src/rawnind/libs/
cp libs/arbitrary_proc_fun.py rawnind_jddc/src/rawnind/libs/
cp libs/raw.py rawnind_jddc/src/rawnind/libs/
cp ../common/libs/icc.py rawnind_jddc/src/common/libs/
cp models/raw_denoiser.py rawnind_jddc/src/rawnind/models/
cp models/manynets_compression.py rawnind_jddc/src/rawnind/models/
cp models/bitEstimator.py rawnind_jddc/src/rawnind/models/
cp models/compression_autoencoders.py rawnind_jddc/src/rawnind/models/
cp ../common/extlibs/gdn.py rawnind_jddc/src/common/extlibs/
cp models/denoise_then_compress.py rawnind_jddc/src/rawnind/models/
cp models/standard_compressor.py rawnind_jddc/src/rawnind/models/
cp ../common/libs/stdcompression.py rawnind_jddc/src/common/libs/
cp tools/find_best_expname_iteration.py rawnind_jddc/src/rawnind/tools/
cp models/bm3d_denoiser.py rawnind_jddc/src/rawnind/models/
cp tools/xtrans_to_openexr_dataset.py rawnind_jddc/src/rawnind/tools/
cp tools/crop_datasets.py rawnind_jddc/src/rawnind/tools/
cp tools/prep_image_dataset.py rawnind_jddc/src/rawnind/tools/
cp libs/rawds_manproc.py rawnind_jddc/src/rawnind/libs/
cp tools/add_msssim_score_to_dataset_yaml_descriptor.py rawnind_jddc/src/rawnind/tools/
cp tools/make_hdr_rawnind_files.py rawnind_jddc/src/rawnind/tools/
cp tools/gather_raw_gt_images.py rawnind_jddc/src/rawnind/tools/
cp tools/make_hdr_extraraw_files.py rawnind_jddc/src/rawnind/tools/
cp tools/prep_image_dataset_extraraw.py rawnind_jddc/src/rawnind/tools/
cp tools/test_all_known.py rawnind_jddc/src/rawnind/tools/
cp tools/test_manproc* rawnind_jddc/src/rawnind/tests/
cp tools/test_ext_raw_denoise* rawnind_jddc/src/rawnind/tests/
cp tools/test_playraw* rawnind_jddc/src/rawnind/tests/
cp tools/validate_and_test* rawnind_jddc/src/rawnind/tests/
cp tools/test_progressive* rawnind_jddc/src/rawnind/tests/
cp config/dt4_xtrans_to_linrec2020.xmp rawnind_jddc/src/rawnind/config/
cp config/graph_dc_models_definitions.yaml rawnind_jddc/src/rawnind/config/
cp config/graph_denoise_models_definitions.yaml rawnind_jddc/src/rawnind/config/
cp config/test_reserve_extdata.yaml rawnind_jddc/src/rawnind/config/
cp config/test_reserve_std.yaml rawnind_jddc/src/rawnind/config/
cp config/test_reserve.yaml rawnind_jddc/src/rawnind/config/
cp config/train_dc_bayer2prgb_preup.yaml rawnind_jddc/src/rawnind/config/
cp config/train_dc_bayer2prgb.yaml rawnind_jddc/src/rawnind/config/
cp config/train_dc_prgb2prgb.yaml rawnind_jddc/src/rawnind/config/
cp config/train_dc_proc2proc.yaml rawnind_jddc/src/rawnind/config/
cp config/train_dc.yaml rawnind_jddc/src/rawnind/config/
cp config/train_denoise_bayer2prgb.yaml rawnind_jddc/src/rawnind/config/
cp config/train_denoise_prgb2prgb.yaml rawnind_jddc/src/rawnind/config/
cp config/train_denoise_proc2proc.yaml rawnind_jddc/src/rawnind/config/
cp config/train_denoise.yaml rawnind_jddc/src/rawnind/config/
cp config/x-trans-to-prgb.dtstyle rawnind_jddc/src/rawnind/config/
cp paper_scripts/* rawnind_jddc/src/rawnind/paper_scripts/
cp plot_cfg/* rawnind_jddc/src/rawnind/plot_cfg/
cp scripts/test_all_needed.sh rawnind_jddc/src/rawnind/scripts/
cp onetimescripts/create_bm3d_argsyaml.py rawnind_jddc/src/rawnind/onetimescripts/
cp onetimescripts/cp_to_repo.sh rawnind_jddc/src/rawnind/onetimescripts/
cp onetimescripts/create_jpegxl_argsyaml.py rawnind_jddc/src/rawnind/onetimescripts/
cp onetimescripts/find_best_bm3d_models_for_given_pictures.py rawnind_jddc/src/rawnind/onetimescripts/
cp onetimescripts/upload_dir_to_dataverse.py rawnind_jddc/src/rawnind/onetimescripts/
cp scripts/mk_denoise_then_compress_models.py rawnind_jddc/src/rawnind/scripts/
cp tests/* rawnind_jddc/src/rawnind/tests/
cp tools/capture_image_set.py rawnind_jddc/src/rawnind/tools/
cp tools/check_dataset.py rawnind_jddc/src/rawnind/tools/
cp tools/cleanup_saved_models_iterations.py rawnind_jddc/src/rawnind/tools/
cp tools/cleanup_saved_models_unused_test_images.py rawnind_jddc/src/rawnind/tools/
cp tools/denoise_image.py rawnind_jddc/src/rawnind/tools/
cp tools/mse.py rawnind_jddc/src/rawnind/tools/
cp tools/rm_empty_models.py rawnind_jddc/src/rawnind/tools/
cp tools/rm_nonbest_model_iterations.py rawnind_jddc/src/rawnind/tools/
cp tools/simple_denoiser.py rawnind_jddc/src/rawnind/tools/
cp tools/summarize_dataset.py rawnind_jddc/src/rawnind/tools/
cp tools/xtrans_to_openexr_dataset.py rawnind_jddc/src/rawnind/tools/
cp README.md rawnind_jddc/src/rawnind/
cp train_* rawnind_jddc/src/rawnind/
cp unittests.py rawnind_jddc/src/rawnind/
cp libs/rawtestlib.py rawnind_jddc/src/rawnind/libs/
cp train_dc_*.py rawnind_jddc/src/rawnind/
cp train_denoiser_*.py rawnind_jddc/src/rawnind/
cp capture_image_set.sh rawnind_jddc/src/rawnind/
